enterpriseId: 1
username: admin
password: admin
xircl: https://docker.sanedsiv.com
fbapi: http://localhost:8002
survey: http://localhost:9090
astra: http://localhost:8410
sender_email: info@sandsiv.com
access_code: some-ac-code
sso: http://sso
sso_api_appname: xircl
sso_api_secret: xircl_secret
sms_gateway_name: TestGateway
sms_sender_name: SENDER_NAME1
sms_phone_number: +380501211111
smstest: http://sms_tester
enterprise: feedback
vocact_case_alert: https://voc.sandsiv.com
vocact_case_alert_token: 72E7352322107B1146337C33EFE9394C
bounce_email_address: bounce@sanedsiv.com
static_link: https://surv.biz/
mysql_host: 127.0.0.1
mysql_port: 3307
mysql_user: root
mysql_pass: root
mongo_uri: 'mongodb://localhost:27077/'
db_feedback: feedback